version: 0.2

phases:
  build:
    commands:
      - echo "Building the Lambda functions..."
      - pwd
      - cd image-index
      - pwd
      - ls
      - zip -r ../image-index.zip *
      - cd ../image_search
      - pwd
      - ls
      - zip -r ../image_search.zip *
      - cd ..
      - ls
      - pwd

  post_build:
    commands:
      - pwd
      - ls
      - echo "Updating the Lambda functions..."
      - aws lambda update-function-code --function-name index-photos --zip-file "fileb://image-index.zip"
      - aws lambda update-function-code --function-name search-photos --zip-file "fileb://image_search.zip"
